version: '3.9'

networks:
  integration-tests:
    driver: bridge

services:
  hangman-front:
    image: binarylavender/hangman-front:latest
    container_name: hangman-front
    depends_on:
      - hangman-api
    ports:
      - "8080:8080"
    environment:
      API_URL: http://localhost:3001
    networks:
      - integration-tests

  hangman-api:
      image: binarylavender/hangman-api:latest
      container_name: hangman-api
      ports:
        - "3001:3000"
      networks:
        - integration-tests

  e2e:
    container_name: cypress
    depends_on:
      - hangman-front
    build:
      context: ../hangman-e2e/e2e
      dockerfile: Dockerfile
    environment:
      - HANGMAN_FRONT_HOST=http://localhost:8080
    # - CYPRESS_baseUrl=http://hangman-front
      - API_URL=http://localhost:3001    
    #command:
    #  [
    #   "./wait-for-it.sh",
    #   "http://localhost:8080",
    #   "--strict",
    #   "--timeout=30",
    #   "--",
    #   "npx","cypress","run"
    #  ]
    #command: npx cypress run
    networks:
      - integration-tests