name: CD - Build and push Docker Image

on:
  pull_request:
    branches: [main]
    paths: ["hangman-api/**"]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-node-build.yml
    with:
      node-version: 16
      working-directory: ./hangman-api

  buildAndPush:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download dist folder as artifact
        uses: actions/download-artifact@v3
        with:
          name: build-code
          path: hangman-api/dist
      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: "jtrillo"
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./hangman-api
          push: true
          tags: jtrillo/hangman-api-actions:v2
          file: ./hangman-api/Dockerfile.workflow
