name: Exercise 3 - Run e2e tests using Cypress Action
 
on:
  workflow_dispatch:

jobs:
  run_e2e_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Run Api service in background
        run: |
          docker run -d -p 3001:3000 ${{ secrets.DOCKER_USER }}/hangman-api:latest
      - name: Run Front service
        run: |
          docker run -d -p 8080:8080 -e API_URL=http://localhost:3001 ${{ secrets.DOCKER_USER }}/hangman-front:latest        
      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./hangman-e2e/e2e