name: Exercise 2 - Docker build and push
 
on:
  workflow_dispatch:   
    inputs:
      working-directory:
        description: 'Working directory to build a Docker Image and Push to Docker Hub'       
        default: 'hangman-front'
        type: choice
        required: true
        options:
          - 'hangman-front'
          - 'hangman-api'

jobs:
  build_and_push_to_registry:
    name: Build and push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: binarylavender
      
    steps:
      - name: Set date tag
        run: |
          echo "CURRENT_DATE=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: ${{ env.DOCKER_USER }}/${{ inputs.working-directory }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest,enable={{is_default_branch}} 
            type=raw,value=${{ env.CURRENT_DATE }}
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}      
      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.working-directory }}
          file: ./${{ inputs.working-directory }}/Dockerfile
          push: true  
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
         